#!/bin/sh

LIBNAME=$1
CVS_ROOT=$2
CVS_MODULE=$3
CVS_TAG=$4

if [ -e ${LIBNAME} ] ; then
  cd ${LIBNAME}
  cvs -z5 up -APd -r ${CVS_TAG}
  cd ..
else
  cvs -z5 -d ${CVS_ROOT} co -d ${LIBNAME} -r ${CVS_TAG} ${CVS_MODULE}
  scripts/dopatch ${LIBNAME}
fi
