#define _ALSOFT_VERSION_MAJOR 1
#define _ALSOFT_VERSION_MINOR 12
#define _ALSOFT_VERSION_BUILD 854

#define _ALSOFT__QUOTE(x) # x
#define _ALSOFT_QUOTE(x) _ALSOFT__QUOTE(x)

#define _ALSOFT_VERSION_STR     \
  _ALSOFT_QUOTE(_ALSOFT_VERSION_MAJOR) "." _ALSOFT_QUOTE(_ALSOFT_VERSION_MINOR) "." _ALSOFT_QUOTE(_ALSOFT_VERSION_BUILD)
